name: eight-days
version: 1.1.0.3

dependencies:
  - base
  - unicode-show

library:
  exposed-modules: EightDays
  source-dirs: src
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - eight-days
      - hspec
